apiVersion: v2
name: smart-basket-umbrella
description: An umbrella Helm chart for Smart Basket application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: smart-basket
    version: 0.1.0
    repository: "file://../smart-basket"
  - name: mongodb
    version: "13.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: redis
    version: "17.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
