apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: SmartBasket
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    privateNetworking: false
    ssh:
      allow: false  # Disable SSH access as per your previous config
    tags:
      # Add any tags you might need
      environment: production
