apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-basket-api
  labels:
    app: smart-basket-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-basket-api
  template:
    metadata:
      labels:
        app: smart-basket-api
    spec:
      containers:
        - name: smart-basket-api
          image: 684626292001.dkr.ecr.us-east-1.amazonaws.com/smart-basket-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: PORT
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: DATABASE_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: JWT_REFRESH_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_REDIRECT_URIS
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: GOOGLE_REDIRECT_URIS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: AWS_REGION
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: FIREBASE_CLIENT_EMAIL
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: FIREBASE_PRIVATE_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: smart-basket-secrets
                  key: STRIPE_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: smart-basket-api
  labels:
    app: smart-basket-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: smart-basket-api
