version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-basket-api
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
    networks:
      - smart-basket-network

  mongo:
    image: mongo:6
    container_name: smart-basket-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - smart-basket-network

volumes:
  mongo_data:

networks:
  smart-basket-network:
    driver: bridge
