# Default values for smart-basket.
replicaCount: 2

image:
  repository: 684626292001.dkr.ecr.us-east-1.amazonaws.com/smartbasket
  pullPolicy: Always
  tag: 'latest'

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: false
  annotations: {}
  name: 'default'

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}

# Environment configuration
environment:
  NODE_ENV: production

# Health check configuration
probes:
  readiness:
    enabled: true
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  liveness:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30

# Secrets configuration (reference to existing secrets)
secrets:
  enabled: true
  name: smart-basket-secrets
